### ISSUE TITLE
possible "bug" fix

### ISSUE THREAD

**Issue by sike417** [Masclaux/LightReader#1]
when i run the program as is on my windows phone 8.1 device, an exception is thrown in file.ts line 12, stating that "access is denied." I have found that by changing the HEAD request to a GET request the exception is no longer thrown. If there was a particular reason why you used a HEAD request in the first place, then you could always stick the HEAD request in a try statement, and only run the GET request, from the catch block, if an exception is thrown.

**Comment by Masclaux** [comment]
Hi.

It's no related to head request. Look like windows phone is more strict on local access.

 Did you run it on device or emulator ?  

I'm currently install windows mobile emulator.

**Comment by sike417** [comment]
Yeah I don't have hyper-v installed, so I ran it on my device.

-----Original Message-----

**Comment by Masclaux** [comment]
Fix with latest commit.

Now you can run application on windows phone 8.

i fixed parser too query selector dont work so i used jquery....

Javascript standart and universal language ... My ass !

**Comment by sike417** [comment]
Excellent. For other small improvements, and question i will probably go with this format and add a new issue. For major things i will send you a pull request. This is my first time actually working with another user on a project, on github, so i am sorta feeling my way around. Also there is a new message for you on the Windows 10 app topic of the baka-tsuki forums.

**Comment by Masclaux** [comment]
Hi

I see the other message but, I miss my pass( found it on my workstation ). 

When you want to push something you just need to make a pull request. I will probably make a code review and integrated it :) .

Just in case don't work on chapter parser is already implemented in the old app.
