### ISSUE TITLE
Find css ui toolKit and made a prototype

### ISSUE THREAD

**Issue by Masclaux** [Masclaux/LightReader#2]
Need a UI ( css ) toolkit who are not too intrusive and look decent. 

Feature needed : 
- navBar : title, back, next/previous chaper 
- dropDown : options, about
- sideBar : chapter list ( on reading mode )
- list item : list of media etc etc 

For prototype maybe take official android app for example.

**Comment by sike417** [comment]
When I get off work I will work on this.

**Comment by Masclaux** [comment]
starting to use ionic
